### ISSUE TITLE
2018 meta issues

### ISSUE THREAD

**Issue by alex-wilmer** [alex-wilmer/rater#29]
- [x] email / password CHANGE TO student ID / 4 digit pin
- [x] no assessment / scoring of other people's images
- [x] can't delete galleries
- [x] fix gallery color changing
- [x] fix star rating
